version: 37
jobs:
- name: Repo Sync Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: VNLib.Core
  - !BranchUpdateTrigger
    projects: VNLib.Core
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Windows Tests
  jobExecutor: windows
  steps:
  - !CheckoutStep
    name: banch checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Initalize dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        task -t .\Module.Taskfile.yaml dev-init
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        task -t .\Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Staging build
  jobExecutor: windows
  steps:
  - !CheckoutStep
    name: clone
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@/'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild Build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay --verbose
        vnbuild publish --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Windows Tests
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Ubuntu Tests
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: banch checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: ubuntu-x64
    runInContainer: true
    image: vnbuild-ubuntu:latest
    interpreter: !DefaultInterpreter
      commands: |
        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Fedora Tests
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: banch checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: fedora-x64
    runInContainer: true
    image: vnbuild-fedora:latest
    interpreter: !DefaultInterpreter
      commands: |
        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Publish master
  jobExecutor: windows
  steps:
  - !CheckoutStep
    name: clone
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@/'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild Build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild Publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400