version: 40
jobs:
- name: Repo Sync Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Windows Tests
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone init and test
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
         git clone @server_url@/@project_path@ --branch @branch@ @project_name@
         cd @project_name@  
         task -t Module.Taskfile.yaml dev-init
         task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone and build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        vnbuild build --no-delay --verbose
        vnbuild publish --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Windows Tests
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Ubuntu Tests
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: checkout source
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: ubuntu-x64 tests
    runInContainer: true
    image: vnuge/vnbuild:ubuntu-latest
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Fedora Tests
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: checkout source
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: fedora-x64 tests
    runInContainer: true
    image: vnuge/vnbuild:fedora-latest
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: clone
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Create git tag
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task tag-current-commit -t Module.Taskfile.yaml
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild Build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay 
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild Publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: ci-tests
  jobExecutor: windows
  steps:
  - !CommandStep
    name: clone deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: run module ci tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        task -t Module.Taskfile.yaml test-ci
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Windows Tests
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
