version: 43
jobs:
- name: Repo Sync Push
  steps:
  - type: PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Core.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: TagCreateTrigger
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Windows Tests
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: Clone init and test
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
         git clone @server_url@/@project_path@ --branch @branch@ @project_name@
         cd @project_name@  
         task -t Module.Taskfile.yaml dev-init
         task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: '** -master'
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Staging build
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: Clone and build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        vnbuild build --no-delay --verbose
        vnbuild publish --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: develop
    userMatch: anyone
  jobDependencies:
  - jobName: Windows Tests
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Ubuntu Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout source
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: ubuntu-x64 tests
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:8.0.415-noble-amd64@@sha256:a0f438b4cfbfd28cefa865facd9d1359732f8fb266a83a515a3634b0e8ac4f0b
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@

        bash ci/scripts/linux-setup-amd64.sh install

        export DOTNET_ROOT=$(pwd)/.dotnet
        export PATH="$PATH:${DOTNET_ROOT}:$HOME/.dotnet/tools"
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: '** -master'
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Fedora Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout source
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: fedora-x64 tests
    runInContainer: true
    image: docker.io/fedora:43@@sha256:2ad3073554aef41c15b2c52e968ec0540c931bc3dab8c599ca6eb6f32f3f2d14
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@

        bash ci/scripts/linux-setup-amd64.sh install

        export DOTNET_ROOT=$(pwd)/.dotnet
        export PATH="$PATH:${DOTNET_ROOT}:$HOME/.dotnet/tools"
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

        task -t Module.Taskfile.yaml dev-init
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: '** -master'
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - type: CommandStep
    name: clone
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Create git tag
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@
        task tag-current-commit -t Module.Taskfile.yaml
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild Build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: "vnbuild build --no-delay \n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild Publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
