# https://taskfile.dev

#Called by the vnbuild system to produce builds for my website
#https://www.vaughnnugent.com/resources/software

#This taskfile is called from the root of a project that is being built
#and the purpose of this taskfile is to package up the output of a build 
#from the solution file, and package it up into a tgz files for distribution

version: '3'

vars:
  BINARY_DIR: 'bin'
  TARGET_FRAMEWORK: '{{ .TARGET_FRAMEWORK | default "net8.0" }}'
  RELEASE_DIR: "./bin/release/{{ .TARGET_FRAMEWORK }}/publish"
  TARGET_DIR: '{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}'

tasks:

  default:
    desc: 'When run from a library directory, builds the managed project'
    dir: "{{ .USER_WORKING_DIR }}"
    vars:
      CONFIGURATION: '{{ .CONFIGURATION | default "release" }}'
    cmds:
     - cmd: cd src/ && 
        dotnet build 
        --configuration {{ .CONFIGURATION }} 
        --verbosity detailed
        {{ .MS_ARGS }} 
        {{ .CLI_ARGS }}    

  #when build succeeds, archive the output into a tgz 
  postbuild_success:
    dir: '{{ .USER_WORKING_DIR }}'
    deps:
     - task: packsource
     
     - task: postbuild
       vars: { BUILD_MODE: debug }
     
     - task: postbuild
       vars: { BUILD_MODE: release }
    cmds:     
     - cmd: echo "Postbuild complete for {{ .PROJECT_NAME }}"
       silent: true

  postbuild:
    dir: '{{ .USER_WORKING_DIR }}'
    internal: false
    vars:
      #the build output directory
      BUILD_OUT: "{{ .BINARY_DIR }}/{{ .BUILD_MODE }}/{{ .TARGET_FRAMEWORK }}/publish"
      #removes unnecessary files from the release packages
      TAR_ARGS: '{{ if eq .BUILD_MODE  "release" }}--exclude="*.pdb" --exclude="*.xml"{{ end }}'
    cmds: 
     - cmd: tar{{ if eq OS "windows" }}.exe{{ end }} 
         -czf "{{ .TARGET_DIR }}/{{ .BUILD_MODE }}.tgz" {{ .TAR_ARGS }}
         -C "{{ .BUILD_OUT }}" .
 
  packsource:
    dir: '{{ .USER_WORKING_DIR }}'
    desc: 'Creates an archive for '
    internal: false
    vars:
      EXCLUDES: 
        --exclude '*obj*'
        --exclude '*bin*'
    cmds:
      - cmd: cd ../ && tar{{ if eq OS "windows" }}.exe{{ end }} 
          {{ .EXCLUDES }}
          -czf "{{ .TARGET_DIR }}/src.tgz" . 

  clean:
    desc: 'Cleans local project artifacts and outputs. Typically called by vnbuild.'
    dir: '{{ .USER_WORKING_DIR }}'
    ignore_error: true
    cmds:
    - for: [ bin/, obj/ ]
      cmd: rm -rf '{{ .ITEM }}'
