<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VNLib.Plugins.Ipc</RootNamespace>
    <AssemblyName>VNLib.Plugins.Ipc</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Vaughn Nugent</Authors>
    <Company>Vaughn Nugent</Company>
    <PackageId>VNLib.Plugins.Ipc</PackageId>
    <Copyright>Copyright © 2026 Vaughn Nugent</Copyright>
    <Description>Provides IPC (inter-plugin communication) primitives, attributes, and runtime injection infrastructure for VNLib plugin assemblies.</Description>
    <PackageProjectUrl>https://www.vaughnnugent.com/resources/software/modules/VNLib.Core</PackageProjectUrl>
    <RepositoryUrl>https://github.com/VnUgE/VNLib.Core/tree/master/lib/Plugins.Ipc</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
