/*
* Copyright (c) 2026 Vaughn Nugent
*
* Library: VNLib
* Package: vnlib_wtlfu
* File: vectors.h
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public License
* as published by the Free Software Foundation; either version 2.1
* of the License, or (at your option) any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public License
* along with vnlib_wtlfu. If not, see http://www.gnu.org/licenses/.
*/

#pragma once

#ifndef VN_VECTORS_H
#define VN_VECTORS_H

#include <stdint.h>

/*
* Golden vector table for wtlHash/wtlHash32 known-answer tests.
* Generated by gen_vectors.c — do not edit by hand.
*/
typedef struct
{
    const char* hex;
    uint32_t    len;
    uint64_t    seed;
    uint64_t    expect_64;
    uint32_t    expect_32;
} wtlfu_vector_t;

#define VEC(hex, len, seed, e64, e32) { (hex), (len), (seed), (e64), (e32) }

/*
* Ascending-byte hex strings: 0x00 0x01 0x02 ... up to the required length.
* C string concatenation splits these across lines for readability.
*/
#define ASC_17 \
    "000102030405060708090a0b0c0d0e0f10"

#define ASC_32 \
    "000102030405060708090a0b0c0d0e0f" \
    "101112131415161718191a1b1c1d1e1f"

#define ASC_64 \
    "000102030405060708090a0b0c0d0e0f" \
    "101112131415161718191a1b1c1d1e1f" \
    "202122232425262728292a2b2c2d2e2f" \
    "303132333435363738393a3b3c3d3e3f"

#define ASC_128 \
    "000102030405060708090a0b0c0d0e0f" \
    "101112131415161718191a1b1c1d1e1f" \
    "202122232425262728292a2b2c2d2e2f" \
    "303132333435363738393a3b3c3d3e3f" \
    "404142434445464748494a4b4c4d4e4f" \
    "505152535455565758595a5b5c5d5e5f" \
    "606162636465666768696a6b6c6d6e6f" \
    "707172737475767778797a7b7c7d7e7f"

#define ASC_129 \
    "000102030405060708090a0b0c0d0e0f" \
    "101112131415161718191a1b1c1d1e1f" \
    "202122232425262728292a2b2c2d2e2f" \
    "303132333435363738393a3b3c3d3e3f" \
    "404142434445464748494a4b4c4d4e4f" \
    "505152535455565758595a5b5c5d5e5f" \
    "606162636465666768696a6b6c6d6e6f" \
    "707172737475767778797a7b7c7d7e7f" \
    "80"

#define ASC_256 \
    "000102030405060708090a0b0c0d0e0f" \
    "101112131415161718191a1b1c1d1e1f" \
    "202122232425262728292a2b2c2d2e2f" \
    "303132333435363738393a3b3c3d3e3f" \
    "404142434445464748494a4b4c4d4e4f" \
    "505152535455565758595a5b5c5d5e5f" \
    "606162636465666768696a6b6c6d6e6f" \
    "707172737475767778797a7b7c7d7e7f" \
    "808182838485868788898a8b8c8d8e8f" \
    "909192939495969798999a9b9c9d9e9f" \
    "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf" \
    "b0b1b2b3b4b5b6b7b8b9babbbcbdbebf" \
    "c0c1c2c3c4c5c6c7c8c9cacbcccdcecf" \
    "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf" \
    "e0e1e2e3e4e5e6e7e8e9eaebecedeeef" \
    "f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"

/*
* Fill-byte hex strings: repeated 0x00 or 0xFF for each path length.
*/
#define ZERO_16 \
    "00000000000000000000000000000000"
#define ZERO_128 \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000"
#define ZERO_256 \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000" \
    "00000000000000000000000000000000"

#define FF_16 \
    "ffffffffffffffffffffffffffffffff"
#define FF_128 \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff"
#define FF_256 \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff" \
    "ffffffffffffffffffffffffffffffff"

static const wtlfu_vector_t VECTORS[] =
{
    /* --- Seed 0 (canonical) --- */
    VEC(NULL,                                  0, 0, 0xEF46DB3751D8E999ULL, 0xBE9E32AE),  /* empty */
    VEC("00",                                  1, 0, 0xE934A84ADB052768ULL, 0x32318F22),  /* 1-byte, short path */
    VEC("0001",                                2, 0, 0x2E3E648F9C9E3AD8ULL, 0xB2A05E57),  /* 2-byte, short path */
    VEC("000102",                              3, 0, 0x52C2F08855A08CABULL, 0x07627C23),  /* 3-byte, switch fall-through */
    VEC("00010203",                            4, 0, 0x5AA21D2074A8BE0FULL, 0x2E0AA32F),  /* 4-byte, 4-8 tier entry */
    VEC("0001020304050607",                    8, 0, 0xC69C6967049BAB2AULL, 0xC207C24D),  /* 8-byte, exactly one read64 */
    VEC("000102030405060708",                  9, 0, 0xD023226130DC1560ULL, 0xE0FF3701),  /* 9-byte, first/last overlap */
    VEC("000102030405060708090a0b0c0d0e0f",   16, 0, 0x8C6DF9E44FF97FE1ULL, 0xC3948605),  /* 16-byte, short path upper bound */

    /* --- Non-zero seed --- */
    VEC("000102030405060708090a0b0c0d0e0f",   16, 0x9E3779B185EBCA87ULL, 0x9E9972449A761075ULL, 0x04EF6231),  /* short + PRIME_1 */
    VEC(ASC_17,                                17, 0x9E3779B185EBCA87ULL, 0x85AB15ADE72FEE64ULL, 0x6284FBC9),  /* medium + PRIME_1 */
    VEC("000102030405060708090a0b0c0d0e0f",   16, 0xFFFFFFFFFFFFFFFFULL, 0x087270C80B7B8BE5ULL, 0x0309FB2D),  /* short + max seed */

    /* --- Ascending-byte inputs --- */
    VEC(ASC_17,                                17, 0, 0x3F70A1C49C682E8FULL, 0xA3188F4B),  /* medium entry */
    VEC(ASC_32,                                32, 0, 0xAE286DEA3368D7D6ULL, 0x9D40BA3C),  /* one medium block */
    VEC(ASC_64,                                64, 0, 0xA3A9A981261ECAC3ULL, 0x85B76342),  /* two medium blocks */
    VEC(ASC_128,                              128, 0, 0x2379C850716EC5FCULL, 0x52170DAC),  /* medium upper bound */
    VEC(ASC_129,                              129, 0, 0xFD5D6FA2A2F12DE7ULL, 0x5FAC4245),  /* long entry */
    VEC(ASC_256,                              256, 0, 0x46D2589DC56A9C22ULL, 0x83B8C4BF),  /* four long blocks */
    VEC(ASC_129,                              129, 0x9E3779B185EBCA87ULL, 0xFAA3298B34212D79ULL, 0xCE8204F2),  /* long + PRIME_1 */
    VEC(ASC_128,                              128, 0xFFFFFFFFFFFFFFFFULL, 0xBF794760C01C7CDCULL, 0x7F653BBC),  /* medium + max seed */
    VEC(ASC_256,                              256, 0xFFFFFFFFFFFFFFFFULL, 0x51B0749D2BA8D6EDULL, 0x7A18A270),  /* long + max seed */

    /* --- Fill-byte inputs --- */
    VEC(ZERO_16,                               16, 0, 0xC6EA0933727BB026ULL, 0xB491B915),  /* all-zeros, short */
    VEC(ZERO_128,                             128, 0, 0xA6F0665EC579507BULL, 0x63893625),  /* all-zeros, medium */
    VEC(ZERO_256,                             256, 0, 0xB911CB60E5519F70ULL, 0x5C405410),  /* all-zeros, long */
    VEC(FF_16,                                 16, 0, 0x54312C65E52EF913ULL, 0xB11FD576),  /* all-0xFF, short */
    VEC(FF_128,                               128, 0, 0x5E29DF670C91168EULL, 0x52B8C9E9),  /* all-0xFF, medium */
    VEC(FF_256,                               256, 0, 0x0A7FA0F3C0C7A9CDULL, 0xCAB8093E),  /* all-0xFF, long */
};

#define VECTOR_COUNT (sizeof(VECTORS) / sizeof(VECTORS[0]))

#endif // !VN_VECTORS_H
